spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ks3-application
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        commit.interval.ms: 1000

kafka:
  topic:
    position-instrument: position-instrument-topic
    gold-smc: gold-smc-topic
    output: enriched-position-instrument-topic 